version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: wb-postgres
    environment:
      POSTGRES_DB: wb_orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nats:
    image: nats-streaming:latest
    container_name: wb-nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-cid", "test-cluster"]
    healthcheck:
      test: ["CMD", "/nats-streaming-server", "-sl"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: